### PR TITLE
40 game facade

### LINKED ISSUE #40: Game Facade
Splitting game responsibilities into different classes.

### PR DESCRIPTION
**Pull request by paultran2**
None of the new classes interact with any of the existing classes (except for the Presenter_Interface). New GameState class is an entity storing the state of the game. Playing cards and card effects are now done in different methods. When a player plays a card, the following methods should be called in this order: play(), checkWin(), doLastPlayedEffect(), setNextTurn(). Card effects (in the LastPlayedEffect class) are not implemented. Generating bot moves and recording games are not implemented. checkWin() only returns a value right now, I'm a bit unsure as to what needs to happen when a game ends.

We should connect the Controller to the GameFacade class and delete the games package.

### CODE REVIEW

**Review by SarahX43 — APPROVED** [review]
Thanks for creating the facade. It helps the game handle all the actions and preserves the SOLID principle. This design pattern also made our program much cleaner.

**Review by NonLan — APPROVED** [review]
This way of formatting our program is definitely a lot better, thanks Paul!

**Review by kovalsviat — APPROVED** [review]
Thanks Paul, a great work. Now we need to connect this to the controller.

**Review by tomwurdfz — APPROVED** [review]
This follows the design pattern we discussed in class, I think it's good to go

**Pull request merged**
