### PR TITLE
Updated Controller and documentation in PlayerRanking.java

### LINKED ISSUE #5: [Feature 7]User Profile System
An user profile system that records user information after each game

### PR DESCRIPTION
**Pull request by tomwurdfz**
Updated Player Ranking in the Controller, Updated documentation in PlayerRanking.java

### CODE REVIEW

**Review by SarahX43 — CHANGES_REQUESTED** [review]
We will still need methods in the presenter that call a method in my view interface to display the actual player ranking page

**Comment by tomwurdfz** [comment]
Updated Presenter and Presenter Interface

**Review by SarahX43 — COMMENTED** [review]
Hi Tom, did you implement the showRanking method?

**Review by NonLan — DISMISSED** [review]

**Review by NonLan — DISMISSED** [review]
This is good for now, but please see Sarah's comment when you get the chance.

**Review by NonLan — APPROVED** [review]

**Pull request merged**
