### PR TITLE
7 feature user profile system

### LINKED ISSUE #5: [Feature 7]User Profile System
An user profile system that records user information after each game

### PR DESCRIPTION
**Pull request by tomwurdfz**
UserProfile Class is ready to go, RecordGame Class needs some testing and probably fixations and methods in PlayerRanking need to be implemented

### CODE REVIEW

**Review by NonLan — APPROVED** [review]

**Comment by NonLan** [comment]
Hey Tom, did you mean to merge this into branch 3? For some reason the default branch got swapped from main to branch 3, so you might want to change the destination if this isn't intentional!

**Review by kovalsviat — APPROVED** [review]
I would like to ask not to include .idea files as it might differ from other .idea files on our own computers. This will affect program settings(I suppose so, as I have already encountered this)
Beside, the code looks good.

**Review by LogicalLunatic — APPROVED** [review]
Current commits looks good

**Comment by SeanGrindal** [comment]
Note that I renamed a function and added specific TODO comments where functions needed to be implemented. I also cleaned up the code so no functions were throwing explicit errors.

**Pull request merged**
